version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: facie_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-friends_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - facie_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facie_api
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-friends_db}
      PYTHONUNBUFFERED: 1
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./app:/app/app
      - media_data:/app/media
      - ./logs:/app/log
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - facie_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level info

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: facie_bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      BACKEND_BASE_URL: ${BACKEND_BASE_URL:-http://api:8000}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./logs:/app/log
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - facie_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python -m bot.main' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  media_data:

networks:
  facie_network:
    driver: bridge